export const IS_CREATE_INSTITUTE_TYPE = "IS_CREATE_INSTITUTE_TYPE";
export const IS_UPDATE_INSTITUTE_TYPE = "IS_UPDATE_INSTITUTE_TYPE";
export const INSTITUTE_TYPE_LIST = "INSTITUTE_TYPE_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
