export const IS_CREATE_DIVISION = "IS_CREATE_DIVISION";
export const IS_UPDATE_DIVISION = "IS_UPDATE_DIVISION";
export const DIVISION_LIST = "DIVISION_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
