export const IS_CREATE_INSTITUTE_NAME = "IS_CREATE_INSTITUTE_NAME";
export const IS_UPDATE_INSTITUTE_NAME = "IS_UPDATE_INSTITUTE_NAME";
export const INSTITUTE_NAME_LIST = "INSTITUTE_NAME_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
