export const IS_CREATE_DISTRICT = "IS_CREATE_DISTRICT";
export const IS_UPDATE_DISTRICT = "IS_UPDATE_DISTRICT";
export const DISTRICT_LIST = "DISTRICT_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
