export const MODERATOR_MONITOR_LIST = "MODERATOR_MONITOR_LIST";
export const IS_MODERATOR_TUTOR_DETAILS = "IS_MODERATOR_TUTOR_DETAILS";
export const MODERATOR_TUTOR_DETAILS = "MODERATOR_TUTOR_DETAILS";
