export const PROFILE_LIST = "PROFILE_LIST";
export const IS_UPDATE_LOADING = "IS_UPDATE_LOADING";
export const PROFILE_DETAILS = "PROFILE_DETAILS";
export const IS_PROFILE_DETAILS_LOADING = "IS_PROFILE_DETAILS_LOADING";
