export const IS_CREATE_AREA = "IS_CREATE_AREA";
export const IS_UPDATE_AREA = "IS_UPDATE_AREA";
export const AREA_LIST = "AREA_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
