export const IS_CREATE_DEPARTMENT_NAME = "IS_CREATE_DEPARTMENT_NAME";
export const IS_UPDATE_DEPARTMENT_NAME = "IS_UPDATE_DEPARTMENT_NAME";
export const DEPARTMENT_NAME_LIST = "DEPARTMENT_NAME_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
