export const IS_CREATE_SUBCATEGORY = "IS_CREATE_SUBCATEGORY";
export const IS_UPDATE_SUBCATEGORY = "IS_UPDATE_SUBCATEGORY";
export const SUBCATEGORY_LIST = "SUBCATEGORY_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const CAT_IMG = "CAT_IMG";
export const IS_IMG_LOADING = "IS_IMG_LOADING";
