export const IS_CREATE_SUBDISTRICT = "IS_CREATE_SUBDISTRICT";
export const IS_UPDATE_SUBDISTRICT = "IS_UPDATE_SUBDISTRICT";
export const SUBDISTRICT_LIST = "SUBDISTRICT_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
