export const IS_CREATE_STUDY_TYPE = "IS_CREATE_STUDY_TYPE";
export const IS_UPDATE_STUDY_TYPE = "IS_UPDATE_STUDY_TYPE";
export const STUDY_TYPE_LIST = "STUDY_TYPE_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const IS_STATUS_UPDATE = "IS_STATUS_UPDATE";
